# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20170708_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjob',
            name='image_filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
