"""
Django settings for ava project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import datetime
import socket

try:
    import ava.secure_settings as secure_settings
except:
    # On development machines, the file secure_settings.py will not exist
    import ava.dev_secure_settings as secure_settings

''' secure_settings.py is not in source control. It contains:

DB_PW = 'databasepassword'
SECRET_KEY = 'djangosecretkey'
PROD_SERVER = False # True for ava.ea.com
DDNS_SERVER = None
DDNS_KEYFILE = None
 '''

ADMIN_EMAIL = 'edanvoye@ea.com'
NOTIFICATION_EMAIL = False
HOSTNAME = socket.gethostname()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DDNS_SERVER = secure_settings.DDNS_SERVER
DDNS_KEYFILE = secure_settings.DDNS_KEYFILE

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secure_settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DATA_UPLOAD_MAX_MEMORY_SIZE=262144000 # 250 MB
FILE_UPLOAD_MAX_MEMORY_SIZE=262144000

ALLOWED_HOSTS = []

# Slack notifications (specify in dev_secure_settings)
SLACK_NOTIF_HOOK = secure_settings.SLACK_NOTIF_HOOK

TAGGIT_CASE_INSENSITIVE = True

# Authentication

#OAUTH2_CLIENT_ID = 'something.apps.googleusercontent.com'
#OAUTH2_CLIENT_SECRET = '000000000000000000000000'
#OAUTH2_REDIRECT_URI = 'http://127.0.0.1:8000/oauth2'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
#    'ava.oauth2.OAuth2Backend',
    )

# Application definition

INSTALLED_APPS = [
    'capture.apps.CaptureConfig',
    'jobs.apps.JobsConfig',
    'archive.apps.ArchiveConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'solo.apps.SoloAppConfig',
    'django.contrib.humanize',
    'django_filters',
    'taggit',
    'taggit_serializer',
    'django_prometheus',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'ava.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ava.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'ava',
        'USER': 'django',
        'PASSWORD': secure_settings.DB_PW,
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',    
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
	'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE' : 1000
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=24*3600),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': '/var/log/django.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'dev': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
ALLOWED_HOSTS = ['ava.ea.com']
LOGIN_URL = '/accounts/login'
FRONTEND_URL = '/d/#'

if not secure_settings.PROD_SERVER: # DEV Server has a different way to serve static files, and more verbose logging

    ALLOWED_HOSTS = ['*']

    # This is a development server
    DEBUG = True
    FRONTEND_URL = STATIC_URL + 'd/index.html#'
    STATICFILES_DIRS = [
        ('thumb', os.path.abspath(os.path.join(BASE_DIR, r'static/thumb'))),
        ('d', os.path.abspath(os.path.join(BASE_DIR, r'dist-dev'))), # path set in docker run
    ]
    DATABASES = {
        'default' : {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR,'dev-database','sqlite3.db'),
        }
    }
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': os.path.join(BASE_DIR, 'debug.log'),
                'formatter': 'verbose'
            },
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'dev': {
                'handlers': ['file'],
                'level': 'DEBUG',
                'propagate': True,
            }
            # ,
            # 'django.db.backends': {
            #     'level': 'DEBUG',
            #     'handlers': ['console'],
            # }            
        },
    }

