# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20170719_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticscanasset',
            name='take_neutral_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticscanasset',
            name='take_neutral_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
