# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('machine_name', models.CharField(max_length=200)),
                ('unique_id', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('using_sync', models.BooleanField(default=False)),
                ('folder', models.CharField(max_length=250)),
                ('thumbnail_filename', models.CharField(max_length=250)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bitdepth', models.IntegerField()),
                ('frame_count', models.IntegerField()),
                ('dropped_frames', models.IntegerField()),
                ('total_size', models.IntegerField()),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='archive.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='archive.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capture_time', models.DateTimeField(auto_now_add=True, verbose_name='capture time')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='archive.Shot')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='archive.Take'),
        ),
    ]
