# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='framerate',
            field=models.FloatField(default=0.0),
        ),
    ]
