# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_camera_framerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='all_files',
            field=models.TextField(null=True),
        ),
    ]
