# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_camera_all_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='bitdepth',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='camera',
            name='total_size',
            field=models.BigIntegerField(),
        ),
    ]
