# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20170320_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='export_path',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
