# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_take_export_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticScanAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image_folder', models.CharField(max_length=255)),
                ('calib_file', models.CharField(max_length=255)),
                ('work_folder', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staticscanasset_related', to='archive.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calib_file', models.CharField(max_length=255)),
                ('start_frame', models.IntegerField(default=0)),
                ('end_frame', models.IntegerField(default=0)),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackingasset_related', to='archive.Take')),
            ],
        ),
    ]
