# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_staticscanasset_trackingasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticscanasset',
            name='thumbnail_filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='take',
            name='video_thumb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trackingasset',
            name='video_thumb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='thumbnail_filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='take',
            name='export_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
