# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20170405_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingasset',
            name='end_frame',
        ),
        migrations.RemoveField(
            model_name='trackingasset',
            name='start_frame',
        ),
        migrations.AddField(
            model_name='trackingasset',
            name='end_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackingasset',
            name='start_time',
            field=models.FloatField(default=0),
        ),
    ]
