# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_camera_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='frontal_cam_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
