# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_session_frontal_cam_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ('unique_id',)},
        ),
        migrations.AlterField(
            model_name='camera',
            name='unique_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
