# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20170531_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticscanasset',
            name='take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staticscanasset_related', to='archive.Take'),
        ),
        migrations.AddField(
            model_name='staticscanasset',
            name='take_mixed_w_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='staticscanasset',
            name='take_pattern_last_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='staticscanasset',
            name='take_pattern_start_time',
            field=models.FloatField(null=True),
        ),
    ]
