# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20170719_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticscanasset',
            name='take_mixed_w_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticscanasset',
            name='take_pattern_last_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticscanasset',
            name='take_pattern_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
