# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('job_class', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('status', model_utils.fields.StatusField(choices=[('created', 'created'), ('ready', 'ready'), ('failed', 'failed'), ('success', 'success')], db_index=True, default='created', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='farmnode',
            name='online',
        ),
        migrations.AddField(
            model_name='farmnode',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='offline', max_length=100, no_check_for_status=True),
        ),
    ]
