# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161011_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnode',
            name='cpu_brand',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='cpu_cores',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='system',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='system_bits',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.FarmNode'),
        ),
    ]
