# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20161013_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnode',
            name='gpu_count',
            field=models.IntegerField(null=True),
        ),
    ]
