# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_farmnode_gpu_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmjob',
            name='params',
            field=models.TextField(null=True),
        ),
    ]
