# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170203_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjob',
            name='dependencies',
            field=models.ManyToManyField(related_name='_farmjob_dependencies_+', to='jobs.FarmJob'),
        ),
        migrations.AddField(
            model_name='farmjob',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.FarmJob'),
        ),
    ]
