# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170309_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmjob',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependants', to='jobs.FarmJob'),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='exception',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.FarmJob'),
        ),
    ]
