# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170317_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjob',
            name='progress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
