# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_farmjob_ext_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjob',
            name='req_version',
            field=models.IntegerField(default=1),
        ),
    ]
