# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_farmjob_req_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnode',
            name='code_version',
            field=models.IntegerField(default=1),
        ),
    ]
