# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20170331_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmjob',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.FarmNode'),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='status_changed',
            field=model_utils.fields.MonitorField(db_index=True, default=django.utils.timezone.now, monitor='status'),
        ),
    ]
