# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_farmnode_code_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnode',
            name='req_restart',
            field=models.BooleanField(default=False),
        ),
    ]
