# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_farmnode_req_restart'),
        ('jobs', '0012_auto_20170401_1527'),
    ]

    operations = [
    ]
