# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_staticscanasset_trackingasset'),
        ('jobs', '0014_merge_20170403_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmjob',
            name='ext_scan_assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_jobs', to='archive.StaticScanAsset'),
        ),
    ]
