# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_farmjob_ext_tracking_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
