# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_farmnode_cpu_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmNodeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='farmnode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='jobs.FarmNodeGroup'),
        ),
    ]
