# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-02 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('jobs', '0022_farmjob_image_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmnode',
            options={'ordering': ['machine_name']},
        ),
        migrations.AddField(
            model_name='farmjob',
            name='mesh_filename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='farmjob',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='aws_auto_shutdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='aws_instance_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='aws_instance_region',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='aws_instance_state',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='none', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='aws_instance_state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='aws_instance_state'),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='git_version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='last_job_activity',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last activity'),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='os_version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='farmnode',
            name='virt_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='req_gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmjob',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
        migrations.AlterField(
            model_name='farmnode',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=200),
        ),
        migrations.AlterField(
            model_name='farmnode',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], db_index=True, default='offline', max_length=100, no_check_for_status=True),
        ),
    ]
