# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CaptureNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('machine_name', models.CharField(max_length=200)),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='last seen')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capture.CaptureNode'),
        ),
    ]
