# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturenode',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='capture.CaptureNode'),
        ),
    ]
