# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_auto_20160929_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_sync_frequency', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Global Configuration',
            },
        ),
    ]
