# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_auto_20161003_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capturenode',
            options={'permissions': (('view_nodes', 'Can see list of nodes and cameras'), ('control_cameras', 'Can change camera settings and record'))},
        ),
    ]
