# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_auto_20161003_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='capturenode',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='capture.CaptureLocation'),
        ),
    ]
