# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capture', '0006_auto_20161004_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_access', models.BooleanField(default=False)),
                ('write_access', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capture.CaptureLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='users',
            field=models.ManyToManyField(related_name='access_rights', through='capture.LocationAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
