# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0007_auto_20161004_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalConfiguration',
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='hardware_sync_frequency',
            field=models.IntegerField(default=30),
        ),
    ]
