# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_auto_20161004_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelocation',
            name='pulse_duration',
            field=models.IntegerField(default=2000),
        ),
    ]
