# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0009_capturelocation_pulse_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='version',
            field=models.CharField(default='', max_length=200),
        ),
    ]
