# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_camera_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturenode',
            name='sync_found',
            field=models.BooleanField(default=False),
        ),
    ]
