# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0011_capturenode_sync_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='exposure',
            field=models.FloatField(default=5000.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='gain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='lens_aperture',
            field=models.FloatField(default=5.6),
        ),
    ]
