# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0013_capturenode_read_access_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturenode',
            name='read_access_all',
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='read_access_all',
            field=models.BooleanField(default=False),
        ),
    ]
