# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_take_sequence'),
        ('capture', '0014_auto_20161121_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelocation',
            name='cur_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Project'),
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='cur_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Session'),
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='cur_shot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Shot'),
        ),
    ]
