# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0016_capturenode_drive_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturenode',
            name='drive_info',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
