# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0017_auto_20161205_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='using_sync',
            field=models.BooleanField(default=False),
        ),
    ]
