# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0018_camera_using_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='using_sync',
            field=models.BooleanField(default=True),
        ),
    ]
