# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0019_auto_20170222_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelocation',
            name='display_focus_peak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='display_histogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capturelocation',
            name='display_overexposed',
            field=models.BooleanField(default=False),
        ),
    ]
