# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0020_auto_20170418_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturelocation',
            name='cur_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Project'),
        ),
        migrations.AlterField(
            model_name='capturelocation',
            name='cur_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Session'),
        ),
        migrations.AlterField(
            model_name='capturelocation',
            name='cur_shot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Shot'),
        ),
    ]
