# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0021_auto_20170418_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
