# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0024_auto_20170617_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturelocation',
            name='external_sync',
            field=models.BooleanField(default=False),
        ),
    ]
