# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0025_capturelocation_external_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturenode',
            name='os',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
